service: rankingservice

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  timeout: 60

functions:
  refreshRanking:
    handler: handler.refresh_ranking
    iamRoleStatements:
      - Effect: Allow
        Action:
          - rekognition:*
          - comprehend:*
          - s3:*
          - rds:*
        Resource: '*'
    events:
      - sqs:
          arn: arn:aws:sqs:eu-central-1:123446374287:coda-crawler.fifo
          batchSize: 5
          # maximumBatchingWindow: 60
          functionResponseType: ReportBatchItemFailures

plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements

#package:
#  patterns:
#    -'!venv/**'
#    -'!node_modules/**'
package:
  individually: true
  exclude:
    - node_modules/**
    - venv/**

custom:
  pythonRequirements:
    dockerizePip: false