service: ranking-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: eu-central-1
package:
  individually: true
  exclude:
    - node_modules/**
    - venv/**
    - query_db/**
    - main.py
    - test_sqs.json.py
    - remove_files.py
    - .git/**
    - .gitignore
    - uml_diagram/**
    - test.py
    - test_sqs.json
    - requirements_eliminati.txt

functions:
  refreshRanking:
    handler: refreshRanking.refresh_ranking
    timeout: 900
    package:
      exclude:
        - 'searchByName.py'
        - 'getLabelAndPost.py'
        - 'getRanking.py'
        - 'favoritesManager.py'
        - 'db/RepositoryExternal.py'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'secretsmanager:GetSecretValue'
        Resource:
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.secretRds}'
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.sercetCredentials}'
      - Effect: Allow
        Action:
          - 'rekognition:DetectFaces'
          - 'rekognition:DetectLabels'
          - 'comprehend:DetectSentiment'
          - 'comprehend:DetectDominantLanguage'
        Resource: '*'
      - Effect: Allow
        Action:
          - 's3:GetObject'
        Resource:
          - "arn:aws:s3:::${self:custom.bucketNameImage}"
          - "arn:aws:s3:::${self:custom.bucketNameImage}/*"
          - "arn:aws:s3:::${self:custom.bucketNameEmoji}"
          - "arn:aws:s3:::${self:custom.bucketNameEmoji}/*"
      - Effect: Allow
        Action:
          - 'rds-data:ExecuteStatement'
          - 'rds-data:BeginTransaction'
          - 'rds-data:CommitTransaction'
          - 'rds-data:BatchExecuteStatement'
        Resource: 'arn:aws:rds:eu-central-1:123446374287:cluster:${self:custom.clusterRds}'
    events:
      - sqs:
          arn: arn:aws:sqs:eu-central-1:123446374287:coda-crawler.fifo
          batchSize: 10
          functionResponseType: ReportBatchItemFailures

  getRanking:
    handler: getRanking.get_ranking
    timeout: 30
    package:
      exclude:
        - 'refreshRanking.py'
        - 'favoritesManager.py'
        - 'getLabelAndPost.py'
        - 'searchByName.py'
        - 'db/RepositoryInternal.py'
        - 'db/RepositoryFavorites.py'
        - 'entity/**'
        - 'analyzer/**'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'secretsmanager:GetSecretValue'
        Resource:
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.secretRds}'
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.sercetCredentials}'
      - Effect: Allow
        Action:
          - 'rds-data:ExecuteStatement'
          - 'rds-data:BeginTransaction'
          - 'rds-data:CommitTransaction'
          - 'rds-data:BatchExecuteStatement'
        Resource: 'arn:aws:rds:eu-central-1:123446374287:cluster:${self:custom.clusterRds}'
      - Effect: "Allow"
        Action:
          - "s3:ListObjects"
          - "s3:GetObject"
        Resource:
          - "arn:aws:s3:::${self:custom.bucketNameImage}"
          - "arn:aws:s3:::${self:custom.bucketNameImage}/*"
    events:
      - http:
          path: getRanking
          method: GET
          cors: true

  getLabelAndPost:
    handler: getLabelAndPost.get_label_and_post
    timeout: 30
    package:
      exclude:
        - 'refreshRanking.py'
        - 'searchByName.py'
        - 'favoritesManager.py'
        - 'getRanking.py'
        - 'db/RepositoryInternal.py'
        - 'db/RepositoryFavorites.py'
        - 'entity/**'
        - 'analyzer/**'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'secretsmanager:GetSecretValue'
        Resource:
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.secretRds}'
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.sercetCredentials}'
      - Effect: Allow
        Action:
          - 'rds-data:ExecuteStatement'
          - 'rds-data:BeginTransaction'
          - 'rds-data:CommitTransaction'
          - 'rds-data:BatchExecuteStatement'
        Resource: 'arn:aws:rds:eu-central-1:123446374287:cluster:${self:custom.clusterRds}'
      - Effect: "Allow"
        Action:
          - "s3:ListObjects"
          - "s3:GetObject"
        Resource:
          - "arn:aws:s3:::${self:custom.bucketNameImage}"
          - "arn:aws:s3:::${self:custom.bucketNameImage}/*"

    events:
      - http:
          path: getLabelAndPost
          method: POST
          cors: true

  searchByName:
    handler: searchByName.search_by_name
    timeout: 30
    package:
      exclude:
        - 'refreshRanking.py'
        - 'favoritesManager.py'
        - 'getLabelAndPost.py'
        - 'getRanking.py'
        - 'db/RepositoryInternal.py'
        - 'db/RepositoryFavorites.py'
        - 'entity/**'
        - 'analyzer/**'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'secretsmanager:GetSecretValue'
        Resource:
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.secretRds}'
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.sercetCredentials}'
      - Effect: Allow
        Action:
          - 'rds-data:ExecuteStatement'
          - 'rds-data:BeginTransaction'
          - 'rds-data:CommitTransaction'
          - 'rds-data:BatchExecuteStatement'
        Resource: 'arn:aws:rds:eu-central-1:123446374287:cluster:${self:custom.clusterRds}'
      - Effect: "Allow"
        Action:
          - "s3:ListObjects"
          - "s3:GetObject"
        Resource:
          - "arn:aws:s3:::${self:custom.bucketNameImage}"
          - "arn:aws:s3:::${self:custom.bucketNameImage}/*"
    events:
      - http:
          path: searchByName
          method: POST
          cors: true

  favorites:
    handler: favoritesManager.favorites_handler
    timeout: 30
    package:
      exclude:
        - 'refreshRanking.py'
        - 'searchByName.py'
        - 'getLabelAndPost.py'
        - 'getRanking.py'
        - 'db/RepositoryInternal.py'
        - 'db/RepositoryExternal.py'
        - 'entity/**'
        - 'analyzer/**'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'secretsmanager:GetSecretValue'
        Resource:
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.secretRds}'
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.sercetCredentials}'
      - Effect: Allow
        Action:
          - 'rds-data:ExecuteStatement'
          - 'rds-data:BeginTransaction'
          - 'rds-data:CommitTransaction'
          - 'rds-data:BatchExecuteStatement'
        Resource: 'arn:aws:rds:eu-central-1:123446374287:cluster:${self:custom.clusterRds}'
    events:
      - http:
          path: favorites
          method: GET
          cors: true

  getCities:
    handler: getCities.get_cities
    timeout: 30
    package:
      exclude:
        - 'refreshRanking.py'
        - 'favoritesManager.py'
        - 'getLabelAndPost.py'
        - 'searchByName.py'
        - 'db/RepositoryInternal.py'
        - 'db/RepositoryFavorites.py'
        - 'entity/**'
        - 'analyzer/**'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'secretsmanager:GetSecretValue'
        Resource:
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.secretRds}'
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.sercetCredentials}'
      - Effect: Allow
        Action:
          - 'rds-data:ExecuteStatement'
          - 'rds-data:BeginTransaction'
          - 'rds-data:CommitTransaction'
          - 'rds-data:BatchExecuteStatement'
        Resource: 'arn:aws:rds:eu-central-1:123446374287:cluster:${self:custom.clusterRds}'
      - Effect: "Allow"
        Action:
          - "s3:ListObjects"
          - "s3:GetObject"
        Resource:
          - "arn:aws:s3:::${self:custom.bucketNameImage}"
          - "arn:aws:s3:::${self:custom.bucketNameImage}/*"
    events:
      - http:
          path: getCities
          method: GET
          cors: true

  filterCoordinate:
    handler: filterCoordinate.filter_coordinate
    timeout: 30
    package:
      exclude:
        - 'refreshRanking.py'
        - 'favoritesManager.py'
        - 'getLabelAndPost.py'
        - 'searchByName.py'
        - 'db/RepositoryInternal.py'
        - 'db/RepositoryFavorites.py'
        - 'entity/**'
        - 'analyzer/**'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'secretsmanager:GetSecretValue'
        Resource:
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.secretRds}'
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.sercetCredentials}'
      - Effect: Allow
        Action:
          - 'rds-data:ExecuteStatement'
          - 'rds-data:BeginTransaction'
          - 'rds-data:CommitTransaction'
          - 'rds-data:BatchExecuteStatement'
        Resource: 'arn:aws:rds:eu-central-1:123446374287:cluster:${self:custom.clusterRds}'
      - Effect: "Allow"
        Action:
          - "s3:ListObjects"
          - "s3:GetObject"
        Resource:
          - "arn:aws:s3:::${self:custom.bucketNameImage}"
          - "arn:aws:s3:::${self:custom.bucketNameImage}/*"
    events:
      - http:
          path: filterCoordinate
          method: GET
          cors: true

  getLabelCucina:
    handler: getLabelCucina.get_label_cucina
    timeout: 30
    package:
      exclude:
        - 'refreshRanking.py'
        - 'favoritesManager.py'
        - 'getLabelAndPost.py'
        - 'searchByName.py'
        - 'db/RepositoryInternal.py'
        - 'db/RepositoryFavorites.py'
        - 'entity/**'
        - 'analyzer/**'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'secretsmanager:GetSecretValue'
        Resource:
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.secretRds}'
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:${self:custom.sercetCredentials}'
      - Effect: Allow
        Action:
          - 'rds-data:ExecuteStatement'
          - 'rds-data:BeginTransaction'
          - 'rds-data:CommitTransaction'
          - 'rds-data:BatchExecuteStatement'
        Resource: 'arn:aws:rds:eu-central-1:123446374287:cluster:${self:custom.clusterRds}'
      - Effect: "Allow"
        Action:
          - "s3:ListObjects"
          - "s3:GetObject"
        Resource:
          - "arn:aws:s3:::${self:custom.bucketNameImage}"
          - "arn:aws:s3:::${self:custom.bucketNameImage}/*"
    events:
      - http:
          path: getLabelCucina
          method: GET
          cors: true


plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements

custom:
  bucketNameImage: dream-team-img-test
  bucketNameEmoji: sweet-emoji-sentiment-scores
  secretRds: SecreteRDS-RxX4ZE
  sercetCredentials: rds-db-credentials/cluster-AQLMTHUP2LEAFVXYXDMZFEHDR4/admin-5WXjei
  clusterRds: sweeat
  pythonRequirements:
    dockerizePip: false