service: ranking-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'rds-data:ExecuteStatement'
        - 'rds-data:BeginTransaction'
        - 'rds-data:CommitTransaction'
        - 'rds-data:BatchExecuteStatement'
      Resource: 'arn:aws:rds:eu-central-1:123446374287:cluster:sweeat'
    - Effect: Allow
      Action:
        - 'secretsmanager:GetSecretValue'
      Resource: 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:SecreteRDS-RxX4ZE'
    - Effect: Allow
      Action:
        - 'secretsmanager:GetSecretValue'
      Resource: 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:rds-db-credentials/cluster-AQLMTHUP2LEAFVXYXDMZFEHDR4/admin-5WXjei'

package:
  individually: true
  exclude:
    - node_modules/**
    - venv/**
    - query_db/**
    - main.py
    - test_sqs.json.py
    - remove_files.py
    - .git/**
    - .gitignore
    - uml_diagram/**
    - test.py
    - test_sqs.json
    - requirements_eliminati.txt

functions:
  refreshRanking:
    handler: refreshRanking.refresh_ranking
    timeout: 900
    package:
      exclude:
        - 'searchByName.py'
        - 'getLabelAndPost.py'
        - 'getRanking.py'
        - 'db/RepositoryExternal.py'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'rekognition:DetectFaces'
          - 'rekognition:DetectLabels'
          - 'comprehend:DetectSentiment'
          - 'comprehend:DetectDominantLanguage'
        Resource: '*'
      - Effect: Allow
        Action:
          - 's3:getObject'
        Resource:
          - "arn:aws:s3:::${self:custom.bucketName}"
          - "arn:aws:s3:::${self:custom.bucketName}/*"
          - "arn:aws:s3:::sweet-emoji-sentiment-scores"
          - "arn:aws:s3:::sweet-emoji-sentiment-scores/*"
      - Effect: Allow
        Action:
          - 'secretsmanager:GetSecretValue'
        Resource:
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:SecreteRDS-RxX4ZE'
          - 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:rds-db-credentials/cluster-AQLMTHUP2LEAFVXYXDMZFEHDR4/admin-5WXjei'
      - Effect: Allow
        Action:
          - 'rds-data:ExecuteStatement'
          - 'rds-data:BeginTransaction'
          - 'rds-data:CommitTransaction'
          - 'rds-data:BatchExecuteStatement'
        Resource: 'arn:aws:rds:eu-central-1:123446374287:cluster:sweeat'
    events:
      - sqs:
          arn: arn:aws:sqs:eu-central-1:123446374287:coda-crawler.fifo
          batchSize: 10
          functionResponseType: ReportBatchItemFailures


  getRanking:
    handler: getRanking.get_ranking
    timeout: 30
    package:
      exclude:
        - 'refreshRanking.py'
        - 'searchByName.py'
        - 'getLabelAndPost.py'
        - 'db/RepositoryInternal.py'
        - 'db/RepositoryFavorites.py'
        - 'entity/**'
        - 'analyzer/**'
    events:
      - http:
          path: getRanking
          method: GET
          cors: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:ListObjects"
          - "s3:GetObject"
        Resource:
          - "arn:aws:s3:::${self:custom.bucketName}"
          - "arn:aws:s3:::${self:custom.bucketName}/*"

  getLabelAndPost:
    handler: getLabelAndPost.get_label_and_post
    timeout: 30
    package:
      exclude:
        - 'refreshRanking.py'
        - 'searchByName.py'
        - 'getRanking.py'
        - 'db/RepositoryInternal.py'
        - 'db/RepositoryFavorites.py'
        - 'entity/**'
        - 'analyzer/**'
    events:
      - http:
          path: getLabelAndPost
          method: POST
          cors: true

  searchByName:
    handler: searchByName.search_by_name
    timeout: 30
    package:
      exclude:
        - 'refreshRanking.py'
        - 'getLabelAndPost.py'
        - 'getRanking.py'
        - 'db/RepositoryInternal.py'
        - 'db/RepositoryFavorites.py'
        - 'entity/**'
        - 'analyzer/**'
    events:
      - http:
          path: searchByName
          method: POST
          cors: true

plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements

custom:
  bucketName: dream-team-img-test
  pythonRequirements:
    dockerizePip: false

#resources:
#  Resources:
#    AssetsBucket:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: ${self:custom.bucketName}


#          - "arn:aws:s3:::dream-team-img-test/*"