service: ranking-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: eu-central-1

functions:
  getRanking:
    handler: getRanking.get_ranking
    timeout: 30
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'rds-data:ExecuteStatement'
        Resource: '*'
      - Effect: Allow
        Action:
          - 'secretsmanager:GetSecretValue'
        Resource: 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:rds-db-credentials/cluster-AQLMTHUP2LEAFVXYXDMZFEHDR4/admin-5WXjei'
    events:
      - http:
          path: getRanking
          method: GET
          cors: true

  getLabelAndPost:
    handler: getLabelAndPost.get_label_and_post
    timeout: 30
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'rds-data:ExecuteStatement'
        Resource: '*'
      - Effect: Allow
        Action:
          - 'secretsmanager:GetSecretValue'
        Resource: 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:rds-db-credentials/cluster-AQLMTHUP2LEAFVXYXDMZFEHDR4/admin-5WXjei'
    events:
      - http:
          path: getLabelAndPost
          method: POST
          cors: true

  refreshRanking:
    handler: refreshRanking.refresh_ranking
    timeout: 900
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'rekognition:DetectFaces'
          - 'rekognition:DetectLabels'
          - 'comprehend:DetectDominantLanguage'
          - 'comprehend:DetectSentiment'
          - 'rds-data:ExecuteStatement'
          - 'rds-data:BeginTransaction'
          - 'rds-data:CommitTransaction'
          - 'rds-data:BatchExecuteStatement'
        Resource: '*'
      - Effect: Allow
        Action:
          - 'secretsmanager:GetSecretValue'
        Resource: 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:rds-db-credentials/cluster-AQLMTHUP2LEAFVXYXDMZFEHDR4/admin-5WXjei'
      - Effect: Allow
        Action:
          - 's3:getObject'
        Resource: "arn:aws:s3:::dream-team-img-test/*"
      - Effect: Allow
        Action:
          - 's3:getObject'
        Resource: "arn:aws:s3:::sweet-emoji-sentiment-scores/*"
    events:
      - sqs:
          arn: arn:aws:sqs:eu-central-1:123446374287:coda-crawler.fifo
          batchSize: 10
          functionResponseType: ReportBatchItemFailures

  searchByName:
    handler: searchByName.search_by_name
    timeout: 30
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'rds-data:ExecuteStatement'
        Resource: '*'
      - Effect: Allow
        Action:
          - 'secretsmanager:GetSecretValue'
        Resource: 'arn:aws:secretsmanager:eu-central-1:123446374287:secret:rds-db-credentials/cluster-AQLMTHUP2LEAFVXYXDMZFEHDR4/admin-5WXjei'
    events:
      - http:
          path: searchByName
          method: POST
          cors: true

package:
  patterns:
    - '!venv/**'
    - '!node_modules/**'
    - '!quey_db/**'
    - '!main.py'
    - '!test_sqs.json.py'
    - '!remove_files.py'

plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
